name:                TrivialPythonFunctionDeclarationParser
version:             0.2.0.0
github:              "breakerzirconia/TrivialPythonFunctionDeclarationParser"
license:             BSD3
author:              "Constantine Ter-Matevosian"
maintainer:          "terkot1010@gmail.com"
copyright:           "2020 Constantine Ter-Matevosian"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TrivialPythonFunctionDeclarationParser#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- graphviz
- array
- process
- mtl

library:
  source-dirs: src

executables:
  TrivialPythonFunctionDeclarationParser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TrivialPythonFunctionDeclarationParser

tests:
  TrivialPythonFunctionDeclarationParser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TrivialPythonFunctionDeclarationParser
